MvcApplication1/MvcApplication1/Controllers/UniversidadeController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using MvcApplication1.Tabelas;

namespace MvcApplication1.Controllers
{
    public class UniversidadeController : Controller
    {
        //
        // GET: /Universidade/

        UniversidadeModel un = new UniversidadeModel();

        public ActionResult Index(string ordem, string busca, string filtro, int? pagina)
        {
            ViewBag.ordemCorrente = ordem;
            ViewBag.nome = ordem == "nomeAsc" ? "nomeDesc" : "nomeAsc";
            ViewBag.cidade = ordem == "cidadeAsc" ? "cidadeDesc" : "cidadeAsc";


            if (!String.IsNullOrEmpty(busca))
            {
                pagina = 1;
            }
            else
            {
                busca = filtro;
            }

            ViewBag.filtro = busca;

            var universidades = un.GetAllUniversidade(ordem, busca, filtro, pagina);

            if (universidades == null)
                return View("NotFound");




            int tamanhoPagina = 5;
            int numPagina = (pagina ?? 1);

            return View(universidades.ToPagedList(numPagina, tamanhoPagina));

        }

        /* 
         * Criar
         * 
         */
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UniversidadeDB nova)
        {
            if (ModelState.IsValid)
            {
                un.insert(nova.nome, nova.cidade);
            }

            return RedirectToAction("index");
        }

        /* 
         * Editar
         *  
         */
        public ActionResult Edit(int id)
        {
            var todos = un.GetAllUniversidade();
            var model = (from p in todos.Where(x => x.universidadeID == id) select p).FirstOrDefault();
            if (model == null)
                return View("NotFound");

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(UniversidadeDB uniEdit)
        {
            if (ModelState.IsValid)
            {
                un.update(uniEdit.universidadeID, uniEdit.nome, uniEdit.cidade);
            }
            return RedirectToAction("index");
        }

        /* 
         * Detalhes
         * 
         */
        public ActionResult Details(int id)
        {

            var log = un.LogUniversidade(id);

            if (log == null)
                return View("NotFound");
            
            return PartialView(log);
        }

        /* 
         * Deletar
         * 
         */

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteView(int id)
        {
            var todos = un.GetAllUniversidade();
            var model = (from p in todos.Where(x => x.universidadeID == id)
                         select p).FirstOrDefault();

            if (model == null)
                return View("NotFound");
            return View(model);

        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                un.delete(id);
                return RedirectToAction("index");
            }
            catch (Exception)
            {
                ViewBag.mensagem = "Não é possível excluir está universidade pois a mesma possui cursos vinculados a ela. Elimine os cursos vinculados a está universidade para prosseguir com sua exclusão!";
                return View("NotFound");
            }

        }

    }
}

MvcApplication1/MvcApplication1/Views/Universidade/Create.cshtml
@model MvcApplication1.Models.UniversidadeDB

@{
    ViewBag.Title = "Create";
}
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Universidade</h2>
        </div>
        <div class="acoes panel body">
            @using (Html.BeginForm("Create", "Universidade", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>Criar</legend>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.nome, "Nome")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.nome, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.nome)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.cidade, "Cidade")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.cidade, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.cidade)
                    </div>
                    <br />
                    <p>
                        <input class="btn btn-primary" type="submit" value="Create" />
                        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
                    </p>
                </fieldset>
            }

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/MvcApplication1/Views/Universidade/Delete.cshtml
@model MvcApplication1.Models.UniversidadeDB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Deseja realmente deletar esta universidade?</h3>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Universidade</h2>
    </div>
    <div class="acoes panel body">
        <table class="table">
            <tr>
                <td>@Html.DisplayNameFor(model => model.universidadeID):</td>
                <td>@Html.DisplayFor(model => model.universidadeID)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.nome):</td>
                <td>@Html.DisplayFor(model => model.nome)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.cidade):</td>
                <td>@Html.DisplayFor(model => model.cidade)</td>
            </tr>

        </table>


        @using (Html.BeginForm("Delete", "Universidade", FormMethod.Post, new { id = Model.universidadeID }))
        {
            <p>
                <input class="btn btn-danger" type="submit" value="Delete" />
                |
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
            </p>
        }
    </div>
</div>

MvcApplication1/MvcApplication1/Views/Universidade/Details.cshtml
@model IEnumerable<MvcApplication1.Models.LogModel>

@{
    ViewBag.Title = "Log";
}
@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Alterado por</th>
                <th>Alterado em</th>
                <th>Universidade</th>
                <th>Cidade</th>
            </tr>
        </thead>

        <tbody>
            @{int i = 1;}
            @foreach (var item in Model)
            {
                <tr>
                    <td>@i</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Autor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Horario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Universidade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CidadeUniversidade)
                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>
}

MvcApplication1/MvcApplication1/Views/Universidade/Edit.cshtml
@model MvcApplication1.Models.UniversidadeDB

@{
    ViewBag.Title = "Editar";
}
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Universidade</h2>
        </div>
        <div class="acoes panel body">
            @using (Html.BeginForm("Edit", "Universidade", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>Editar</legend>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.nome, "Nome")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.nome, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.nome)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.cidade, "Cidade")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.cidade, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.cidade)
                    </div>
                    <br />
                    <p>
                        <input class="btn btn-primary" type="submit" value="Create" />
                        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
                    </p>
                </fieldset>
            }

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/MvcApplication1/Views/Universidade/Index.cshtml
@model PagedList.IPagedList<MvcApplication1.Models.UniversidadeDB>
@using PagedList;
@using PagedList.Mvc;


@{
    ViewBag.Title = "Universidade";
}
<h2>Universidades</h2>
<p>
    @Html.ActionLink("Nova universidade", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar para Home", "Index", "Home", null, new { @class = "btn btn-default" })
</p>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Universidade</h2>
    </div>
    <div class="acoes panel body">
        @using (Html.BeginForm("Index", "Universidade", FormMethod.Get))
        {
            <p>
                @Html.TextBox("busca", ViewBag.filtro as string, new { @class = "busca" })
                <input type="submit" value="Buscar" class="btn btn-default" />
            </p>
        }
        <br />
        <table class="table table-condensed table-hover">
            <tr>
                <th>
                    @Html.ActionLink("Nome", "Index", new { ordem = ViewBag.nome, filtro = ViewBag.filtro })
                </th>
                <th>
                    @Html.ActionLink("Cidade", "Index", new { ordem = ViewBag.cidade, filtro = ViewBag.filtro })
                </th>
                <th>
                    <!-- empty -->
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cidade)
                    </td>
                    <td id="td-botoes">
                        @Ajax.ActionLink("Log", "Details", new { id = item.universidadeID }, new AjaxOptions() { HttpMethod = "GET", OnSuccess = "retornoLog" }, new { @class = "detalhar btn btn-default btn-sm" })
                        @Html.ActionLink("Editar", "Edit", new { id = item.universidadeID }, new { @class = "btn btn-default btn-sm" })
                        @Html.ActionLink("Excluir", "Delete", new { id = item.universidadeID }, new { @class = "btn btn-default btn-sm" })
                    </td>
                </tr>
            }

        </table>
        <p>
            Página 
            @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            de 
            @Model.PageCount
            @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, ordem = ViewBag.ordemCorrente, filtro = ViewBag.filtro }))
        </p>
    </div>
</div>


    @* Modal de detalhes *@
<!-- Small modal -->
<div class="detalhes modal fade" id="detalhes" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" style="margin-top: 10%;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Log</h4>
            </div>
            <div class="modal-body">
                @{Html.RenderPartial("Details", new List<MvcApplication1.Models.LogModel>());}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Voltar</button>
            </div>
        </div>
    </div>
</div>