MvcApplication1/MvcApplication1/Controllers/AlunoController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MvcApplication1.Controllers
{
    public class AlunoController : Controller
    {

        //
        // GET: /Aluno/
        AlunoModel al = new AlunoModel();

        public ActionResult Index(string ordem, string busca, string filtro, int? pagina)
        {
            ViewBag.ordemCorrente = ordem;
            ViewBag.aluno = ordem == "alunoAsc" ? "alunoDesc" : "alunoAsc";
            ViewBag.email = ordem == "emailAsc" ? "emailDesc" : "emailAsc";
            ViewBag.data = ordem == "dataAsc" ? "dataDesc" : "dataAsc";
            ViewBag.universidade = ordem == "universidadeAsc" ? "universidadeDesc" : "universidadeAsc";
            ViewBag.curso = ordem == "cursoAsc" ? "cursoDesc" : "cursoAsc";

            if (!String.IsNullOrEmpty(busca))
            {
                pagina = 1;
            }
            else
            {
                busca = filtro;
            }

            ViewBag.filtro = busca;

            var universidades = al.GetAllAlunos(ordem, busca, filtro, pagina);

            if (universidades == null)
                return View("NotFound");

            int tamanhoPagina = 5;
            int numPagina = (pagina ?? 1);

            return View(universidades.ToPagedList(numPagina, tamanhoPagina));
        }

        /* 
         * Criar
         * 
         */
        public ActionResult Create()
        {

            ViewBag.universidade = carregaUniversidade();
            ViewBag.curso = carregaCursoList(universidadeSelect, 0);

            return View();
        }

        [HttpPost]
        public ActionResult Create(AlunoDB novo, int universidade, int curso)
        {
            novo.cursoID = curso;
            novo.universidadeID = universidade;

            try
            {
                al.insert(novo.alunoNome, novo.alunoEmail, novo.dataNascimento, novo.cursoID);
            }
            catch (Exception)
            {
                Console.WriteLine("Não foi possível inserir o aluno");
            }

            return RedirectToAction("index");
        }

        /* 
         * Editar
         *  
         */
        public ActionResult Edit(int id)
        {
            var todos = al.GetAllAlunos();
            var model = (from p in todos.Where(x => x.alunoID == id)
                         select p).FirstOrDefault();


            ViewBag.universidade = carregaUniversidade(model.universidadeID);

            ViewBag.curso = carregaCursoList(model.universidadeID, model.cursoID);

            if (model == null)
                return View("NotFound");

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(AlunoDB alunoEdit, int universidade, int curso)
        {

            if (verificaSePossuiNota(alunoEdit) ||
               (alunoEdit.universidadeID == universidade && alunoEdit.cursoID == curso))
            {
                alunoEdit.universidadeID = universidade;
                alunoEdit.cursoID = curso;

                al.update(alunoEdit.alunoID, alunoEdit.alunoNome, alunoEdit.alunoEmail, alunoEdit.dataNascimento, alunoEdit.cursoID);
            }
            else
            {
                ViewBag.mensagem = "O aluno " + alunoEdit.alunoNome + " possui notas informadas, sendo que não é possível alterar o curso ou a universidade neste caso.";
                return View("NotFound");
            }
            return RedirectToAction("index");
        }

        /* 
         * Detalhes
         * 
         */
        public ActionResult Details(int id)
        {

            var log = al.Log(id);
            if (log == null)
                return View("NotFound");

            return PartialView(log);

        }

        /* 
         * Deletar
         * 
         */

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteView(int id)
        {

            var todos = al.GetAllAlunos();
            var model = (from p in todos.Where(x => x.alunoID == id)
                         select p).FirstOrDefault();

            if (model == null)
                return View("NotFound");

            return View(model);

        }

        [HttpPost]
        public ActionResult Delete(int id)
        {

            try
            {
                al.delete(id);
            }
            catch (Exception)
            {
                ViewBag.mensagem = "O aluno possui notas vinculadas, não sendo possível apagar o mesmo antes que suas notas sejam apagadas";
                return View("NotFound");
            }

            return RedirectToAction("index");
        }




        /*********************************************************
         * 
         * 
         * 
         * 
         * Métodos auxiares
         * 
         * 
         *********************************************************/
        UniversidadeModel uni = new UniversidadeModel();
        CursoModel cur = new CursoModel();

        public int universidadeSelect { get; set; }

        // Chamado no Create
        public IEnumerable<SelectListItem> carregaUniversidade()
        {
            var listaUni = uni.GetAllUniversidade();

            List<SelectListItem> itens = new List<SelectListItem>();

            universidadeSelect = 0;

            itens.Add(new SelectListItem { Text = "Selecione...", Value = 0.ToString(), Selected = true });

            foreach (var item in listaUni)
            {
                itens.Add(new SelectListItem { Text = item.nome, Value = item.universidadeID.ToString() });
            }

            return itens;
        }

        // Chamado no Edit
        public IEnumerable<SelectListItem> carregaUniversidade(int universidade)
        {

            var listaUni = uni.GetAllUniversidade();

            List<SelectListItem> itens = new List<SelectListItem>();

            universidadeSelect = 0;

            foreach (var item in listaUni)
            {
                if (universidadeSelect == 0)
                {
                    itens.Add(new SelectListItem { Text = "Selecione...", Value = 0.ToString(), Selected = false });
                    universidadeSelect = universidade;
                }

                if (item.universidadeID == universidade)
                    itens.Add(new SelectListItem { Text = item.nome, Value = item.universidadeID.ToString(), Selected = true });
                else
                    itens.Add(new SelectListItem { Text = item.nome, Value = item.universidadeID.ToString(), Selected = false });
            }

            return itens;
        }

        //Chamado via Ajax/Jquery
        [ActionName("carregaCurso")]
        [HttpPost]
        public JsonResult carregaCurso(int universidade)
        {

            var listaCur = cur.GetAllCursos();

            List<SelectListItem> itens = new List<SelectListItem>();

            foreach (var item in listaCur)
            {
                if (item.universidadeID == universidade)
                {
                    itens.Add(new SelectListItem { Text = item.nome, Value = item.cursoID.ToString() });
                }
            }

            return Json(itens, JsonRequestBehavior.AllowGet);
        }

        // Chamado no e no create edit
        public IEnumerable<SelectListItem> carregaCursoList(int universidade, int curso)
        {
            var listaCur = cur.GetAllCursos();

            List<SelectListItem> itens = new List<SelectListItem>();

            itens.Add(new SelectListItem { Text = "Selecione...", Value = 0.ToString(), Selected = true });

            if (universidade != 0)
                foreach (var item in listaCur)
                {
                    if (item.universidadeID == universidade && universidade != 0)
                    {
                        if (curso != 0 && item.cursoID == curso)
                            itens.Add(new SelectListItem { Text = item.nome, Value = item.cursoID.ToString(), Selected = true });
                        else
                            itens.Add(new SelectListItem { Text = item.nome, Value = item.cursoID.ToString(), Selected = false });
                    }
                }

            return itens;
        }



        public Boolean verificaSePossuiNota(AlunoDB aluno)
        {

            NotasModel notas = new NotasModel();
            var listaNotas = notas.GetAllNotas();


            foreach (var item in listaNotas)
            {
                if (item.alunoID == aluno.alunoID)
                    return false;
            }
            return true;
        }



    }
}

MvcApplication1/MvcApplication1/Views/Aluno/Create.cshtml
@model MvcApplication1.Models.AlunoDB

@{
    ViewBag.Title = "Create";
}
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Disciplina</h2>
        </div>
        <div class="acoes panel body">

            @using (Html.BeginForm("Create", "aluno", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <fieldset>
                    <legend>Criar</legend>

                    @Html.HiddenFor(model => model.cursoID)
                    @Html.HiddenFor(model => model.universidadeID)

                    <div class="editor-label">
                        @Html.LabelFor(model => model.alunoNome, "Nome")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.alunoNome , new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.alunoNome)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.alunoEmail, "Email")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.alunoEmail, new { @class = "form-control", type = "email" })
                        @Html.ValidationMessageFor(model => model.alunoEmail)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.dataNascimento, "Data de Nascimento")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.dataNascimento, null, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.dataNascimento)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.universidadeID, "Universidade")
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("universidade", null, new { @class = "form-control" })
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.cursoID, "Curso")
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("curso", null, new { @class = "form-control" })
                    </div>

                    <br />

                    <p>
                        <input class="btn btn-primary" type="submit" value="Criar" />
                        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
                    </p>
                </fieldset>
            }
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/MvcApplication1/Views/Aluno/Delete.cshtml
@model MvcApplication1.Models.AlunoDB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@Html.AntiForgeryToken()

<h3>Deseja realmente deletar este Aluno?</h3>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Aluno</h2>
    </div>
    <div class="acoes panel body">

        <table>
            <tr>
                <td>@Html.DisplayNameFor(model => model.alunoID):</td>
                <td>@Html.DisplayFor(model => model.alunoID)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.alunoNome):</td>
                <td>@Html.DisplayFor(model => model.alunoNome)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.alunoEmail):</td>
                <td>@Html.DisplayFor(model => model.alunoEmail)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.dataNascimento):</td>
                <td>@Html.DisplayFor(model => model.dataNascimento)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.cursoNome):</td>
                <td>@Html.DisplayFor(model => model.cursoNome)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.universidadeNome):</td>
                <td>@Html.DisplayFor(model => model.universidadeNome)</td>
            </tr>
        </table>

        @using (Html.BeginForm("Delete", "aluno", FormMethod.Post, new { id = Model.alunoID }))
        {
            <p>
                <input class="btn btn-danger" type="submit" value="Delete" />
                |
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
            </p>
        }
    </div>
</div>

MvcApplication1/MvcApplication1/Views/Aluno/Details.cshtml
@model IEnumerable<MvcApplication1.Models.LogModel>

@{
    ViewBag.Title = "Log";
}
@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Alterado por</th>
                <th>Alterado em</th>
                <th>Nome</th>
                <th>Data de Nascimento</th>
                <th>Email</th>
                <th>Curso</th>
                <th>Universidade</th>
            </tr>
        </thead>

        <tbody>
            @{int i = 1;}
            @foreach (var item in Model)
            {
                <tr>
                    <td>@i</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Autor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Horario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Aluno)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AlunoNascimento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AlunoEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Curso)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Universidade)
                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>
}

MvcApplication1/MvcApplication1/Views/Aluno/Edit.cshtml
@model MvcApplication1.Models.AlunoDB

@{
    ViewBag.Title = "Editar";
}
<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Disciplina</h2>
        </div>
        <div class="acoes panel body">

            @using (Html.BeginForm("Edit", "aluno", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <fieldset>
                    <legend>Editar</legend>
                    @Html.HiddenFor(model => model.alunoID)
                    @Html.HiddenFor(model => model.cursoID)
                    @Html.HiddenFor(model => model.universidadeID)

                    <div class="editor-label">
                        @Html.LabelFor(model => model.alunoNome, "Nome")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.alunoNome , new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.alunoNome)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.alunoEmail, "Email")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.alunoEmail, new { @class = "form-control", type = "email" })
                        @Html.ValidationMessageFor(model => model.alunoEmail)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.dataNascimento, "Data de Nascimento")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.dataNascimento, null, new { @class = "form-control"})
                        @Html.ValidationMessageFor(model => model.dataNascimento)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.universidadeID, "Universidade")
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("universidade", null, new { @class = "form-control" })
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.cursoID, "Curso")
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("curso", null, new { @class = "form-control" })
                    </div>

                    <br />

                    <p>
                        <input class="btn btn-primary" type="submit" value="Salvar" />
                        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
                    </p>
                </fieldset>
            }
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/MvcApplication1/Views/Aluno/Index.cshtml
@model PagedList.IPagedList<MvcApplication1.Models.AlunoDB>
@using PagedList;
@using PagedList.Mvc;


@{
    ViewBag.Title = "Alunos";
}

<h2>Alunos</h2>

<p>
    @Html.ActionLink("Criar novo aluno", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar para Home", "Index", "Home", null, new { @class = "btn btn-default" })
</p>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Aluno</h2>
    </div>
    <div class="acoes panel body">

        @using (Html.BeginForm("Index", "Aluno", FormMethod.Get))
        {
            <p>
                @Html.TextBox("busca", ViewBag.filtro as string, new { @class = "busca" })
                <input type="submit" value="Buscar" class="btn btn-default" />
            </p>
        }

        <table class="table table-condensed table-hover">
            <tr>
                <th>

                    @Html.ActionLink("Aluno", "Index", new { ordem = ViewBag.aluno, filtro = ViewBag.filtro })
                </th>
                <th>
                    @Html.ActionLink("Email", "Index", new { ordem = ViewBag.email, filtro = ViewBag.filtro })
                </th>
                <th>
                    @Html.ActionLink("Data Nascimento", "Index", new { ordem = ViewBag.data, filtro = ViewBag.filtro })
                </th>
                <th>
                    @Html.ActionLink("Curso", "Index", new { ordem = ViewBag.curso, filtro = ViewBag.filtro })
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.alunoNome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.alunoEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.dataNascimento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cursoNome)
                    </td>
                    
                    <td id="td-botoes">
                        @Ajax.ActionLink("Log", "Details", new { id = item.alunoID }, new AjaxOptions() { HttpMethod = "GET", OnSuccess = "retornoLog" }, new { @class = "detalhar btn btn-default btn-sm" })
                        @Html.ActionLink("Editar", "Edit", new { id = item.alunoID }, new { @class = "btn btn-default btn-sm" })
                        @Html.ActionLink("Excluir", "Delete", new { id = item.alunoID }, new { @class = "btn btn-default btn-sm" })
                    </td>
                </tr>
            }

        </table>
        <div>
            Página 
            @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            de 
            @Model.PageCount
            @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, ordem = ViewBag.ordemCorrente, filtro = ViewBag.filtro }))
        </div>
    </div>
</div>


@* Modal de detalhes *@
<!-- Small modal -->
<div class="detalhes modal fade" id="detalhes" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" style="margin-top: 10%;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Log</h4>
            </div>
            <div class="modal-body">
                @{Html.RenderPartial("Details", new List<MvcApplication1.Models.LogModel>());}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Voltar</button>
            </div>
        </div>
    </div>
</div>