MvcApplication1/MvcApplication1/Controllers/NotasController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MvcApplication1.Controllers
{
    public class NotasController : Controller
    {
        //
        // GET: /Notas/

        NotasModel no = new NotasModel();

        public ActionResult Index(string ordem, string busca, string filtro, int? pagina)
        {
            ViewBag.ordemCorrente = ordem;
            ViewBag.aluno = ordem == "alunoAsc" ? "alunoDesc" : "alunoAsc";
            ViewBag.disciplina = ordem == "disciplinaAsc" ? "disciplinaDesc" : "disciplinaAsc";
            ViewBag.nota = ordem == "notaAsc" ? "notaDesc" : "notaAsc";

            if (!String.IsNullOrEmpty(busca))
            {
                pagina = 1;
            }
            else
            {
                busca = filtro;
            }

            ViewBag.filtro = busca;

            var universidades = no.GetAllNotas(ordem, busca, filtro, pagina);

            if (universidades == null)
                return View("NotFound");

            int tamanhoPagina = 5;
            int numPagina = (pagina ?? 1);

            return View(universidades.ToPagedList(numPagina, tamanhoPagina));
        }

        /* 
         * Criar
         * 
         */
        public ActionResult Create()
        {
            ViewBag.aluno = carregaAluno();
            ViewBag.disciplina = carregaDisciplinaList(cursoAluno);
            return View();
        }

        [HttpPost]
        public ActionResult Create(NotasDB novo, int aluno, int disciplina)
        {
            try
            {

                novo.alunoID = aluno;
                novo.disciplinaID = disciplina;

                no.insert(novo.alunoID, novo.disciplinaID, novo.nota);
            }
            catch(Exception)
            {   
                ViewBag.mensagem = "Não foram informados todos os parâmetros necessários";
                return View("NotFound");
            }

            return RedirectToAction("index");
        }

        /* 
         * Editar
         *  
         */
        public ActionResult Edit(int alunoID, int disciplinaID)
        {
            NotasDB model = retornaUmRegistro(alunoID, disciplinaID);

            if (model == null)
                return View("NotFound");

            ViewBag.curso = carregaAluno(alunoID);
            ViewBag.disciplina = carregaDisciplinaList(cursoAluno);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(NotasDB notas)
        {
            if (ModelState.IsValid)
            {
                no.update(notas.alunoID, notas.disciplinaID, notas.nota);
            }
            return RedirectToAction("index");
        }

        /* 
         * Detalhes
         * 
         */
        public ActionResult Details(int alunoID, int disciplinaID)
        {

            NotasDB model = retornaUmRegistro(alunoID, disciplinaID);

            if (model == null)
                return View("NotFound");

            return View(model);

        }

        /* 
         * Deletar
         * 
         */
        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteView(int alunoID, int disciplinaID)
        {
            NotasDB model = retornaUmRegistro(alunoID, disciplinaID);

            if (model == null)
                return View("NotFound");

            return View(model);

        }

        [HttpPost]
        public ActionResult Delete(NotasDB notas, int alunoID, int disciplinaID)
        {
            no.delete(alunoID, disciplinaID);

            return RedirectToAction("index");
        }

        /*
         *Alterações e métodos gerais.
         * utilizados pelas rotinas principais
         * da manutenção da base de dados
         */


        public NotasDB retornaUmRegistro(int alunoID, int disciplinaID)
        {
            var todos = no.GetAllNotas();
            var model = (from p in todos.Where(x => x.alunoID == alunoID && x.disciplinaID == disciplinaID)
                         select p).FirstOrDefault();

            return model;
        }


        /*********************************************************
         * 
         * 
         * 
         * 
         * Métodos auxiares
         * 
         * 
         *********************************************************/
        AlunoModel al = new AlunoModel();
        DisciplinaModel dis = new DisciplinaModel();
        CursoModel cur = new CursoModel();

        public int cursoAluno { get; set; }
        public int alunoSelect { get; set; }

        // Chamado no Create
        public IEnumerable<SelectListItem> carregaAluno()
        {
            var alunos = al.GetAllAlunos();

            List<SelectListItem> itens = new List<SelectListItem>();

            itens.Add(new SelectListItem { Text = "Selecione...", Value = 0.ToString(), Selected = true });

            foreach (var item in alunos)
            {
                itens.Add(new SelectListItem { Text = item.alunoNome, Value = item.alunoID.ToString() });
            }

            return itens;
        }

        // Chamado no Edit
        public IEnumerable<SelectListItem> carregaAluno(int aluno)
        {

            var alunos = al.GetAllAlunos();

            List<SelectListItem> itens = new List<SelectListItem>();

            alunoSelect = 0;

            itens.Add(new SelectListItem { Text = "Selecione...", Value = 0.ToString(), Selected = false });
            foreach (var item in alunos)
            {
                if (alunoSelect == 0)
                {
                    alunoSelect = aluno;
                }

                if (item.universidadeID == aluno)
                    itens.Add(new SelectListItem { Text = item.alunoNome, Value = item.alunoID.ToString(), Selected = true });
                else
                    itens.Add(new SelectListItem { Text = item.alunoNome, Value = item.alunoID.ToString(), Selected = false });
            }

            return itens;
        }

        //Chamado via Ajax/Jquery
        [ActionName("carregaDisciplinas")]
        [HttpPost]
        public JsonResult carregaDisciplinas(int aluno)
        {
            //Seleciona o objeto especifico do aluno que foi selecionado
            var todos = al.GetAllAlunos();
            var alunoDB = (from p in todos.Where(x => x.alunoID == aluno) select p).FirstOrDefault();

            var listaDisciplinas = dis.GetAllDisciplinas();

            List<SelectListItem> itens = new List<SelectListItem>();

            foreach (var item in listaDisciplinas)
            {
                if (item.cursoID == alunoDB.cursoID)
                {
                    itens.Add(new SelectListItem { Text = item.nomeDisciplina, Value = item.disciplinaID.ToString() });
                }
            }

            return Json(itens, JsonRequestBehavior.AllowGet);
        }

        // Chamado no e no create edit
        public IEnumerable<SelectListItem> carregaDisciplinaList(int curso)
        {
            DisciplinaModel dis = new DisciplinaModel();

            var listaDisciplinas = dis.GetAllDisciplinas();

            List<SelectListItem> itens = new List<SelectListItem>();

            itens.Add(new SelectListItem { Text = "Selecione...", Value = 0.ToString(), Selected = true });

            if (curso != 0)
                foreach (var item in listaDisciplinas)
                {
                    if (item.cursoID == curso)
                    {
                        itens.Add(new SelectListItem { Text = item.nomeDisciplina, Value = item.disciplinaID.ToString(), Selected = false });
                    }
                }
            return itens;
        }
    }
}

MvcApplication1/MvcApplication1/Views/Notas/Create.cshtml
@model MvcApplication1.Models.NotasDB

@{
    ViewBag.Title = "Create";
}


<h2>Criar</h2>

<div class="acoes">
    @using (Html.BeginForm("Create", "Notas", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Notas</legend>


            @Html.HiddenFor(model => model.alunoID)

            <div class="editor-label">
                <b>aluno</b>
            </div>

            <div class="editor-field">
                @Html.DropDownList("aluno")
            </div>

            <div class="editor-label">
                <b>Disciplina</b>
            </div>

            <div class="editor-field">
                @Html.DropDownList("disciplina")
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.nota)
            </div>

            <div class="editor-field">
                @Html.EditorFor(model => model.nota)
                @Html.ValidationMessageFor(model => model.nota)
            </div>

            <br />

            <p>
                <input class="btn btn-success" type="submit" value="Create" />
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
            </p>
        </fieldset>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/MvcApplication1/Views/Notas/Delete.cshtml
@model MvcApplication1.Models.NotasDB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@Html.AntiForgeryToken()

<h3>Deseja realmente deletar esta nota</h3>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Notas</h2>
    </div>
    <div class="acoes panel body">
        <table class="table">
            <tr>
                <td>#ID</td>
                <td>@Html.DisplayFor(model => model.alunoID)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.alunoNome):</td>
                <td>@Html.DisplayFor(model => model.alunoNome)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.disciplinaNome):</td>
                <td>@Html.DisplayFor(model => model.disciplinaNome)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.nota):</td>
                <td>@Html.DisplayFor(model => model.nota)</td>
            </tr>
        </table>



        @using (Html.BeginForm("Delete", "Notas", FormMethod.Post, new { alunoID = Model.alunoID, disciplinaID = Model.disciplinaID }))
        {
            @Html.HiddenFor(model => model.alunoID)
            @Html.HiddenFor(model => model.disciplinaID)
            <p>
                <input class="btn btn-danger" type="submit" value="Delete" />
                |
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
            </p>
        }
    </div>
</div>

MvcApplication1/MvcApplication1/Views/Notas/Details.cshtml
@model MvcApplication1.Models.NotasDB

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes das notas</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Notas</h2>
    </div>
    <div class="acoes panel body">
        <table class="table">
            <tr>
                <th>@Html.DisplayNameFor(model => model.alunoID)</th>
                <th>@Html.DisplayNameFor(model => model.alunoNome)</th>
                <th>@Html.DisplayNameFor(model => model.disciplinaID)</th>
                <th>@Html.DisplayNameFor(model => model.disciplinaNome)</th>
                <th>@Html.DisplayNameFor(model => model.nota)</th>
            </tr>
            <tr>
                <td>@Html.DisplayFor(model => model.alunoID)</td>
                <td>@Html.DisplayFor(model => model.alunoNome)</td>
                <td>@Html.DisplayFor(model => model.disciplinaID)</td>
                <td>@Html.DisplayFor(model => model.disciplinaNome)</td>
                <td>@Html.DisplayFor(model => model.nota)</td>
            </tr>

        </table>


        <p>
            @Html.ActionLink("Editar", "Edit", new { alunoID = Model.alunoID, disciplinaID = Model.disciplinaID }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
        </p>
    </div>
</div>

MvcApplication1/MvcApplication1/Views/Notas/Edit.cshtml
@model MvcApplication1.Models.NotasDB

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Notas</h2>
    </div>
    <div class="acoes panel body">
        @using (Html.BeginForm("Edit", "Notas", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <fieldset>
                <legend>Notas</legend>

                @Html.HiddenFor(model => model.alunoID)
                @Html.HiddenFor(model => model.disciplinaID)

                <div class="editor-label">
                    @Html.DisplayFor(model => model.alunoNome)
                </div>
                <div class="editor-label">
                    @Html.DisplayFor(model => model.disciplinaNome)
                </div>

                <div class="editor-field">
                    @Html.EditorFor(model => model.nota)
                    @Html.ValidationMessageFor(model => model.nota)
                </div>
                <br />
                <p>
                    <input class="btn btn-success" type="submit" value="Save" />|
            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
                </p>
            </fieldset>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/MvcApplication1/Views/Notas/Index.cshtml
@model PagedList.IPagedList<MvcApplication1.Models.NotasDB>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Notas";
}

<h2>Notas</h2>
<p>
    @Html.ActionLink("Cria novo", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar para home", "Index", "Home", null, new { @class = "btn btn-default" })
</p>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Notas</h2>
    </div>
    <div class="acoes panel body">

        @using (Html.BeginForm("Index", "Notas", FormMethod.Get))
        {
            <p>
                @Html.TextBox("busca", ViewBag.filtro as string, new { @class = "busca" })
                <input type="submit" value="Buscar" class="btn btn-default" />
            </p>
        }

        <table class="table table-condensed table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.ActionLink("Aluno", "Index", new { ordem = ViewBag.aluno, filtro = ViewBag.filtro })
                    </th>
                    <th>
                        @Html.ActionLink("Disciplina", "Index", new { ordem = ViewBag.disciplina, filtro = ViewBag.filtro })
                    </th>
                    <th>
                        @Html.ActionLink("Nota", "Index", new { ordem = ViewBag.nota, filtro = ViewBag.filtro })
                    </th>
                    <th>
                        <!-- Empty -->
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    @Html.HiddenFor(modelItem => item.alunoID)
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.alunoNome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.disciplinaNome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.nota)
                        </td>
                        <td id="td-botoes">
                            @Html.ActionLink("Detalhar", "Details", new { alunoID = item.alunoID, disciplinaID = item.disciplinaID }, new { @class = "btn btn-default btn-sm" })
                            @Html.ActionLink("Editar", "Edit", new { alunoID = item.alunoID, disciplinaID = item.disciplinaID }, new { @class = "btn btn-default btn-sm" })
                            @Html.ActionLink("Excluir", "Delete", new { alunoID = item.alunoID, disciplinaID = item.disciplinaID }, new { @class = "btn btn-default btn-sm" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            Página 
            @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            de 
            @Model.PageCount
            @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, ordem = ViewBag.ordemCorrente, filtro = ViewBag.filtro }))
        </div>
    </div>
</div>