MvcApplication1/MvcApplication1/Controllers/CursoController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using PagedList;

namespace MvcApplication1.Controllers
{
    public class CursoController : Controller
    {
        //
        // GET: /Curso/ 

        CursoModel cm = new CursoModel();

        public ActionResult Index(string ordem, string busca, string filtro, int? pagina)
        {
            ViewBag.ordemCorrente = ordem;
            ViewBag.curso = ordem == "cursoAsc" ? "cursoDesc" : "cursoAsc";
            ViewBag.universidade = ordem == "universidadeAsc" ? "universidadeDesc" : "universidadeAsc";

            if (!String.IsNullOrEmpty(busca))
            {
                pagina = 1;
            }
            else
            {
                busca = filtro;
            }

            ViewBag.filtro = busca;

            var cursos = cm.GetAllCursos(ordem, busca, filtro, pagina);

            if (cursos == null)
                return View("NotFound");

            int tamanhoPagina = 5;
            int numPagina = (pagina ?? 1);

            return View(cursos.ToPagedList(numPagina, tamanhoPagina));
        }
        /* 
         * Criar
         * 
         */
        public ActionResult Create()
        {

            ViewBag.listaUniversidade = carregaListaUni();


            return View();
        }

        [HttpPost]
        public ActionResult Create(CursoDB novo, int listaUniversidade)
        {

            novo.universidadeID = listaUniversidade;

            cm.insert(novo.nome, novo.universidadeID);


            return RedirectToAction("index");
        }






        /* 
         * Editar
         *  
         */
        public ActionResult Edit(int id)
        {
            var todos = cm.GetAllCursos();
            var model = (from p in todos.Where(x => x.cursoID == id)
                         select p).FirstOrDefault();

            ViewBag.listaUniversidade = carregaListaUni(model.universidadeID);

            if (model == null)
                return View("NotFound");

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CursoDB cursoEdit, int listaUniversidade)
        {
            // move o retorno da DropDownView, caso contrário ficará com o valor antigo na hora de atualizar o registro
            cursoEdit.universidadeID = listaUniversidade;

            if (ModelState.IsValid)
            {
                cm.update(cursoEdit.cursoID, cursoEdit.nome, cursoEdit.universidadeID);
            }

            return RedirectToAction("index");
        }





        /* 
         * Detalhes
         * 
         */
        public ActionResult Details(int id)
        {
            var log = cm.Log(id);
            
            if (log == null)
                return View("NotFound");

            return PartialView(log);

        }

        /* 
         * Deletar
         * 
         */

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteView(int id)
        {

            var todos = cm.GetAllCursos();
            var model = (from p in todos.Where(x => x.cursoID == id)
                         select p).FirstOrDefault();

            if (model == null)
                return View("NotFound");

            return View(model);

        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                cm.delete(id);
            }
            catch (Exception)
            {
                ViewBag.mensagem = "O curso possui alunos vinculados, não sendo permitida a exclusão do mesmo";
                return View("NotFound");
                
            }
            return RedirectToAction("index");
        }





        /*
         * Métodos auxiliares para as principais funções do controller 
         * 
         */
        public IEnumerable<SelectListItem> carregaListaUni()
        {

            UniversidadeModel uni = new UniversidadeModel();
            var lista = uni.GetAllUniversidade();

            List<SelectListItem> itens = new List<SelectListItem>();

            foreach (var item in lista)
            {
                itens.Add(new SelectListItem { Text = item.nome, Value = item.universidadeID.ToString() });
            }

            return itens;
        }

        public IEnumerable<SelectListItem> carregaListaUni(int universidade)
        {

            UniversidadeModel uni = new UniversidadeModel();
            var lista = uni.GetAllUniversidade();

            List<SelectListItem> itens = new List<SelectListItem>();

            foreach (var item in lista)
            {
                if (item.universidadeID == universidade)
                    itens.Add(new SelectListItem { Text = item.nome, Value = item.universidadeID.ToString(), Selected = true });
                else
                    itens.Add(new SelectListItem { Text = item.nome, Value = item.universidadeID.ToString(), Selected = false });


            }

            return itens;
        }




        // Tentativa de criar um DropDownList, porém não consegui mover o mesmo para a view
        //public DropDownList carregaListaUni()
        //{

        //    UniversidadeModel uni = new UniversidadeModel();
        //    var lista = uni.GetAllUniversidade();

        //    CursoDB cdb = new CursoDB();

        //    DropDownList ddlUniversidade = new DropDownList();
        //    ddlUniversidade.DataSource = lista;
        //    ddlUniversidade.DataTextField = "nome";
        //    ddlUniversidade.DataValueField = "universidadeID";
        //    ddlUniversidade.DataBind();

        //    return ddlUniversidade;
        //}
    }
}

MvcApplication1/MvcApplication1/Views/Curso/Create.cshtml
@model MvcApplication1.Models.CursoDB

@{
    ViewBag.Title = "Create";
}

<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Curso</h2>
        </div>
        <div class="acoes panel body">
            @using (Html.BeginForm("Create", "curso", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>Criar</legend>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.nome, "Nome:")
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.nome, htmlAttributes: new { @class="form-control"})
                        @Html.ValidationMessageFor(model => model.nome)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.universidadeID, "Universidade:")
                    </div>
                    <div class="editor-field">
                        @Html.DropDownList("listaUniversidade", null, htmlAttributes: new { @class="form-control"})
                    </div>
                    <br />
                    <p>
                        <input class="btn btn-primary" type="submit" value="Create" />
                        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
                    </p>
                </fieldset>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/MvcApplication1/Views/Curso/Delete.cshtml
@model MvcApplication1.Models.CursoDB

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@Html.AntiForgeryToken()

<h3>Deseja realmente deletar este curso?</h3>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Curso</h2>
    </div>
    <div class="acoes panel body">
        <table class="table">
            <tr>
                <td>@Html.DisplayNameFor(model => model.cursoID):</td>
                <td>@Html.DisplayFor(model => model.cursoID)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.nome):</td>
                <td>@Html.DisplayFor(model => model.nome)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.universidadeID):</td>
                <td>@Html.DisplayFor(model => model.universidadeID)</td>
            </tr>

            <tr>
                <td>@Html.DisplayNameFor(model => model.universidadeNome):</td>
                <td>@Html.DisplayFor(model => model.universidadeNome)</td>
            </tr>

        </table>

        <br />
        @using (Html.BeginForm("Delete", "Curso", FormMethod.Post, new { id = Model.cursoID }))
        {
            <p>
                <input class="btn btn-danger" type="submit" value="Delete" />
                |
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
            </p>
        }
    </div>
</div>

MvcApplication1/MvcApplication1/Views/Curso/Details.cshtml
@model IEnumerable<MvcApplication1.Models.LogModel>

@{
    ViewBag.Title = "Log";
}
@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Alterado por</th>
                <th>Alterado em</th>
                <th>Nome</th>
                <th>Universidade</th>
            </tr>
        </thead>

        <tbody>
            @{int i = 1;}
            @foreach (var item in Model)
            {
                <tr>
                    <td>@i</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Autor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Horario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Curso)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Universidade)
                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>
}

MvcApplication1/MvcApplication1/Views/Curso/Edit.cshtml
@model MvcApplication1.Models.CursoDB

@{
    ViewBag.Title = "Edit";
}

<div class="col-md-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Curso</h2>
        </div>
        <div class="acoes panel body">
            @using (Html.BeginForm("Edit", "Curso", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>Editar</legend>

                    @Html.HiddenFor(model => model.cursoID)
                    @Html.HiddenFor(model => model.universidadeID)


                    <div class="editor-label">
                        @Html.LabelFor(model => model.nome, "Nome:")
                    </div>

                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.nome, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.nome)
                    </div>
                    <!--divisão dos campos -->
                    <div class="editor-label">
                        @Html.LabelFor(model => model.universidadeID, "Universidade:")
                    </div>
                    <div>
                        @Html.DropDownList("listaUniversidade", null, htmlAttributes: new { @class = "form-control" })
                    </div>

                    <br />

                    <p>
                        <input class="btn btn-primary" type="submit" value="Salvar" />
            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
                    </p>
                </fieldset>
            }
        </div>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/MvcApplication1/Views/Curso/Index.cshtml
@model PagedList.IPagedList<MvcApplication1.Models.CursoDB>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Cursos";
}

<h2>Cursos</h2>

<p>
    @Html.ActionLink("Criar novo curso", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Voltar para Home", "Index", "Home", null, new { @class = "btn btn-default" })
</p>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title">Curso</h2>
    </div>
    <div class="acoes panel body">

        @using (Html.BeginForm("Index", "Curso", FormMethod.Get))
        {
            <p>
                @Html.TextBox("busca", ViewBag.filtro as string, new { @class = "busca" })
                <input type="submit" value="Buscar" class="btn btn-default" />
            </p>
        }

        <table class="table table-condensed table-hover">
            <tr>
                <th>
                    @Html.ActionLink("Curso", "Index", new { ordem = ViewBag.curso, filtro = ViewBag.filtro })
                </th>
                <th>
                    @Html.ActionLink("Universidade", "Index", new { ordem = ViewBag.universidade, filtro = ViewBag.filtro })
                </th>
                <th>
                    <!-- empty -->
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UniversidadeNome)
                    </td>
                    <td id="td-botoes">
                        @Ajax.ActionLink("Log", "Details", new { id = item.cursoID }, new AjaxOptions() { HttpMethod = "GET", OnSuccess = "retornoLog" }, new { @class = "detalhar btn btn-default btn-sm" })
                        @Html.ActionLink("Editar", "Edit", new { id = item.cursoID }, new { @class = "btn btn-default btn-sm" })
                        @Html.ActionLink("Excluir", "Delete", new { id = item.cursoID }, new { @class = "btn btn-default btn-sm" })
                    </td>
                </tr>
            }

        </table>
        <div>
            Página 
            @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            de 
            @Model.PageCount
            @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, ordem = ViewBag.ordemCorrente, filtro = ViewBag.filtro }))
        </div>
    </div>
</div>
    @* Modal de detalhes *@
<!-- Small modal -->
<div class="detalhes modal fade" id="detalhes" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" style="margin-top: 10%;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Log</h4>
            </div>
            <div class="modal-body">
                @{Html.RenderPartial("Details", new List<MvcApplication1.Models.LogModel>());}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Voltar</button>
            </div>
        </div>
    </div>
</div>